# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160301_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubs', to='core.Publisher'),
        ),
    ]
