# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160301_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pubs', to='core.Publisher'),
        ),
    ]
