# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160307_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128, verbose_name='NAME1'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
