# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160309_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('remark', models.CharField(max_length=255, verbose_name='remark')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
        ),
    ]
