# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('owners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.Account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(through='demo1.Projects', to='demo1.Account'),
        ),
    ]
